name: codeowners-validator

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron:  '0 8 * * *'
  repository_dispatch:
    types: run-branch-master

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository, which is validated in the next step
      - uses: actions/checkout@v2
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.4.4
        with:
          checks: "files,owners,duppatterns"
          experimental_checks: "notowned"
          # GitHub access token is required only if the `owners` check is enabled
          github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
