name: codeowners-validator

on:
  repository_dispatch:
    types: run-branch-failures

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository, which is validated in the next step
      - uses: actions/checkout@v2
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@canary
        env:
          INPUT_GITHUB_ACCESS_TOKEN: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
