name: codeowners-validator-happy-path

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository, which is validated in the next step
      - uses: actions/checkout@v3
        with:
          ref: happy-path
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.7.4 # ./ # Uses an action in the root directory
        with:
          checks: "files,owners,duppatterns,syntax"
          experimental_checks: "notowned,avoid-shadowing"
          github_app_id: ${{ secrets.APP_ID }}
          github_app_installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          github_app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
